### ISSUE TITLE
Could you include yaml files for conref in this project?

### ISSUE THREAD

**Issue by JiniousChoi** [IBM-Bluemix-Docs/openwhisk#48]
as the title says

**Comment by JiniousChoi** [comment]
Or, would you point me to some where I can find them?

**Comment by Rachael-Graham** [comment]
Thanks for your interest in how our documentation project works behind the scenes. Unfortunately we can’t release the conrefs that we have for the documentation because they are unique to our docs build process. Is there a reason that you wanted to see the conrefs or is there something I might be able to help with?

**Comment by JiniousChoi** [comment]
I am building our own version of docs for a project of our own based upon openwhisk. 
I thought I could make a good use of your conrefs to build our own.
I understand what you mean. On second thought, I think I am okay with the official docs included in incubator-openwhisk projec. Thanks for your attention :)

**Comment by Rachael-Graham** [comment]
No problem! :)
